{"name": "test_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2", "trace": "self = <test.test_api.test_001.Test_login object at 0x00000129702FEBA8>\n\n    def test_004(self):\n>       assert 1==2\nE       assert 1 == 2\nE         -1\nE         +2\n\ntest_001.py:42: AssertionError"}, "start": 1617889053884, "stop": 1617889053885, "uuid": "8d967887-f724-4a77-b3c1-063cf330cb3c", "historyId": "f2ddd476985c6e8779dc7ea5f1bb8ec9", "testCaseId": "e1f1ef64cd04debae6bd8a4c4456aba1", "fullName": "test.test_api.test_001.Test_login#test_004", "labels": [{"name": "parentSuite", "value": "test.test_api"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-5T9ABC0"}, {"name": "thread", "value": "20088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api.test_001"}]}